# Generated by Django 4.1.7 on 2023-03-14 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Literature', '0003_remove_novel_img_novel_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='literature',
            name='author',
        ),
    ]
