# Generated by Django 4.1.7 on 2023-03-14 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Literature', '0004_remove_literature_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ancient_Poetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='题目')),
                ('context', models.TextField(verbose_name='内容')),
                ('create_time', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Modern_Poetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='题目')),
                ('context', models.TextField(verbose_name='内容')),
                ('create_time', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
