# Generated by Django 4.1.7 on 2023-03-14 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Literature', '0005_ancient_poetry_modern_poetry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ancient_Poetry',
        ),
        migrations.DeleteModel(
            name='Modern_Poetry',
        ),
    ]
