# Generated by Django 4.1.7 on 2023-03-24 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Literature', '0007_modern_poetry_ancient_poetry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novel',
            name='literature_type',
        ),
    ]
