# Generated by Django 4.1.7 on 2023-03-24 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Literature', '0008_remove_novel_literature_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novel',
            name='cover',
            field=models.GenericIPAddressField(verbose_name='封面'),
        ),
    ]
